/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#5d1900",
        "on-error-container": "#ffdad6",
        "tertiary": "#4edea3",
        "surface": "#0d141c",
        "on-tertiary-container": "#003a25",
        "primary-fixed": "#ffdbd0",
        "outline-variant": "#594139",
        "inverse-primary": "#ab3500",
        "tertiary-container": "#00af79",
        "on-secondary-fixed": "#000d60",
        "on-secondary-fixed-variant": "#062acf",
        "on-primary-fixed": "#390c00",
        "on-error": "#690005",
        "surface-container-lowest": "#080f16",
        "surface-container-high": "#242b33",
        "surface-container": "#192028",
        "secondary-fixed": "#dfe0ff",
        "on-tertiary": "#003824",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-container": "#0d2ed1",
        "surface-bright": "#333a43",
        "on-secondary-container": "#aab3ff",
        "inverse-on-surface": "#2a313a",
        "surface-tint": "#ffb59d",
        "on-tertiary-fixed": "#002113",
        "primary-fixed-dim": "#ffb59d",
        "on-background": "#dce3ee",
        "surface-container-highest": "#2e353e",
        "on-secondary": "#001a97",
        "surface-dim": "#0d141c",
        "inverse-surface": "#dce3ee",
        "surface-variant": "#2e353e",
        "error": "#ffb4ab",
        "on-surface": "#dce3ee",
        "outline": "#a98a80",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#5f1900",
        "background": "#0d141c",
        "on-surface-variant": "#e1bfb5",
        "tertiary-fixed": "#6ffbbe",
        "primary-container": "#ff6b35",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#832600",
        "secondary-fixed-dim": "#bcc3ff",
        "primary": "#ffb59d",
        "surface-container-low": "#151c24",
        "secondary": "#bcc3ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "margin": "2.5rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Syne"],
        "body-sm": ["Space Grotesk"],
        "label-lg": ["Space Grotesk"],
        "display-hero-mobile": ["Syne"],
        "display-hero": ["Syne"],
        "body-lg": ["Space Grotesk"],
        "label-sm": ["Space Grotesk"],
        "headline-sm": ["Syne"],
        "headline-lg": ["Syne"],
        "label-md": ["Space Grotesk"],
        "body-md": ["Space Grotesk"],
        "headline-md": ["Syne"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display-hero-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
